export const RESET = "RESET";
export const NEW_CARD = "NEW_CARD";
export const NEW_TOMBOLONE = "NEW_TOMBOLONE";
export const NEW_TOMBOLONE_NUMBER = "NEW_TOMBOLONE_NUMBER";
export const SELECT_NUMBER = "SELECT_NUMBER";
export const RESTORE_STATE = "RESTORE_STATE";

// PUSHED UPDATES
export const UPDATE_SESSION_CONTROLLER_STATUS =
  "UPDATE_SESSION_CONTROLLER_STATUS";
export const UPDATE_TOMBOLONE_BUTTON_STATUS = "UPDATE_TOMBOLONE_BUTTON_STATUS";
export const UPDATE_TOMBOLONE_NUMBER = "UPDATE_TOMBOLONE_NUMBER";
export const SET_PUSHER_API_SETTINGS = "SET_PUSHER_API_SETTINGS";
